export const LOGIN_ACTION = 'LOGIN_ACTION'
export const LOGOUT_ACTION = 'LOGOUT_ACTION'
export const REMEMBER_PASSWORD_ACTION = 'REMEMBER_PASSWORD_ACTION'
export const SETUSERINFO_ACTION = 'SETUSERINFO_ACTION'